{% set version = "1.0.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidymultiqc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/TidyMultiqc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/TidyMultiqc/TidyMultiqc_{{ version }}.tar.gz
  sha256: face354ea86a639625b90376a52d53529f25d5b4b4bfb4f990821e7aedc08f29

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-histdat >=0.2.0
    - r-assertthat
    - r-dplyr
    - r-jsonlite
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tibble
  run:
    - r-base
    - r-histdat >=0.2.0
    - r-assertthat
    - r-dplyr
    - r-jsonlite
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-stringr
    - r-tibble

test:
  commands:
    - $R -e "library('TidyMultiqc')"           # [not win]
    - "\"%R%\" -e \"library('TidyMultiqc')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=TidyMultiqc
  license: GPL-3.0-or-later
  summary: Converts 'MultiQC' Reports into Tidy Data Frames
  description: Provides the means to convert 'multiqc_data.json' files, produced by the wonderful 'MultiQC' tool, into tidy data frames for downstream analysis in R. This analysis might involve cohort analysis, quality control visualisation, change-point detection, statistical process control, clustering, or any other type
    of quality analysis.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - epruesse
